FactoryGirl.define do
  factory :politican do
    member_id "MyString"
    api_uri "MyString"
    first_name "MyString"
    last_name "MyString"
    date_of_birth "MyString"
    party "MyString"
    twitter_account "MyString"
    facebook_account "MyString"
    youtube_account "MyString"
    govtrack_id "MyString"
    cspan_id "MyString"
    votesmart_id "MyString"
    icpsr_id "MyString"
    crp_id "MyString"
    fec_candidate_id "MyString"
    next_election "MyString"
    missed_votes "MyString"
    total_present "MyString"
    ocd_id "MyString"
    office "MyString"
    phone "MyString"
    state "MyString"
    lis_id "MyString"
    missed_votes_pct "MyString"
    votes_with_party_pct "MyString"
  end
end
